import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/main-header/main-header";
import { ShareContextProvide } from "@/store/share-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ShareContextProvide>
      <html lang="en">
        <body>
          <MainHeader />

          {children}
        </body>
      </html>
    </ShareContextProvide>
  );
}
