"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/main-header/main-header";
import { ShareContextProvide } from "@/store/share-context";

import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
interface RootProps {
  children: React.ReactNode;
  // pageProps:any
  
}

export default function RootLayout({ children }: RootProps): JSX.Element {
  return (
    <SessionProvider>
      <ShareContextProvide>
        <html lang="en">
          <body>
            <MainHeader />
            {children}
          </body>
        </html>
      </ShareContextProvide>
    </SessionProvider>
  );
}
